services:
  - type: web
    name: portfolio-fullstack
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build && cd .. && cd backend && npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
